### ISSUE TITLE
Passive Mob Count

### ISSUE THREAD

**Issue by Master-Jynx** [DevOnTheRocks/SkyClaims#103]
### Version:
I'm Mod on the network so I dont have version info acccess
but this isn't a bug report, its part complaint and part request for information

We have several sponge servers running 1.12.2 modpacks such as Sky factory 3, StoneBlock 2 and Sky Advetures With GP and Sky Claims.
The issue we are having is with the Living Entity counts are not accurate.
Islands with only 12 chickens (no other animals present) will have a population of 60 listed.
an Island  with zero animals will a count of 48  and a limit of 50
We're looking for a way to limit aniamal pop per island but can't , because we dont know what SC counting.
Players get frustarted because they can't regulate the populations on their islands.
information on what SC considers to be an animal i that count is appreciated.

**Comment by Mohron** [comment]
Passive mobs are a combination of all entities that extend Animal, Aquatic, or Ambient.  When it comes to vanilla, those types are easily defined but when it comes to Mod entities, it depends on how the developer decided to impliment their mob. The data used by SkyClaims' feature is taken straight from Sponge.

https://github.com/DevOnTheRocks/SkyClaims/blob/d5701823f8ab179b0db7fadbfd143582111a4965/src/main/java/net/mohron/skyclaims/listener/EntitySpawnHandler.java#L64-L65

**Comment by Master-Jynx** [comment]
thank you for your response

**Comment by Mohron** [comment]
So if you can identify what entities are being reported on each island, you can better identify why the numbers are different than expected.

**Comment by Master-Jynx** [comment]
thats our problem, we dont know what they are or from what mod.
a knewly created SF3 island consists of 1 tree, 1 dirt block, 1 player and 
a count of 40+ passive animals with a limit of 70 set

**Comment by Mohron** [comment]
I could probably make some modifications that would help you identify your issue, but you would need to have your server administrator on board with using a custom SkyClaims version.

**Comment by Master-Jynx** [comment]
I have to speak with a specific person. which i will, it may take a day or 2 before hes online.
Thank You

**Comment by SeanStoves** [comment]
We would happily take a custom version.   We were actually about to modify /is info ourselves to list out all the entities that were being counted, however, I'm sure you would be quicker as making that a build then we would be at getting to it since we are working our way through a rather extensive list on multiple servers.

SpongeForge
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-c675e80
SpongeForge: 1.10.2-2477-5.2.0-BETA-2793
Minecraft Forge: 12.18.3.2477

SkyClaims-0.27.2-S5.1-BETA.jar
griefprevention-1.10.2-4.0.1.566.jar

**Comment by Mohron** [comment]
https://github.com/DevOnTheRocks/SkyClaims/tree/feature/entity-info

I haven't gotten the chance to test and verify any of this but I think I have a good start. The only issue is, originally you were talking about 1.12.2 which I still support but now you're talking about 1.10.2 which I no longer support. I wanted to help you with this issue because I felt there was value added in a better entity feature to include in future versions. I won't directly support 1.10.2 but you're welcome to use the command I've started to build a custom 1.10.2 version.

**Comment by SeanStoves** [comment]
I will take a look, and backport it to 1.10.   If I don't do that route for the added command, I will just add a list entity under the /is info as a quick and dirty.  Thanks for the idea + code that you have right now :)

**Comment by Mohron** [comment]
If you do backport my new command, I fully intend to support the command so I welcome your feedback as it was a quick and dirty implementation of the idea I had in my head. And if you are using 1.12.2 skyclaims, this command will certianly be released there when it's ready.

**Comment by Mohron** [comment]
Also once we can identify your specific issue, I feel that an entity blacklist/whitelist may be next on the list to handle problems like this in the future.
