### ISSUE TITLE
expand infinitely with /is info and clicking a old sponge callback button

### ISSUE THREAD

**Issue by Bucky420** [DevOnTheRocks/SkyClaims#105]
if u do /claiminfo u can expand your claim past your limits and bypass it by clicking a older expand button that came before. 

sponge 3616 
latest plugin build

**Comment by Mohron** [comment]
So it's GP's `/claiminfo` command that's doing this? Because I realized that `/is info` would have this bug as well.

**Comment by Bucky420** [comment]
the /is info and clicking the expand button my bad made this when i was sleepy

**Comment by Mohron** [comment]
So if you check `/is info` after, you'll see that it doesn't actually expand past 512 x 512. The message being incorrect I already have a fix ready for. Are you expecting that the limit matches the island owners limit? Because as a Admin option, I left it uncapped though I could see the benefit of there at least being a warning.

**Comment by Bucky420** [comment]
no i had it hit like 800 ....

**Comment by Mohron** [comment]
Fixed in 584c92fb132f9943c73e8a28e082bc72d9da477b. Will be released in the next update.
