### ISSUE TITLE
Island Deleting Command

### ISSUE THREAD

**Issue by Rage-GitHub** [DevOnTheRocks/SkyClaims#114]
It would be nice if you can toggle an option to either teleport players back to spawn after deleting it or to teleport them to a friends island, or just let them fall to the void.

Also can you make a template for suggestions?

**Comment by Mohron** [comment]
How exactly would you expect "a friends island" to be decided by the plugin? Also dropping them into the void is not only a horrible "feature", if you leave a player in range of any massive block editing, their client almost always becomes out of sync with the world. That ultimately forces the player to disconnect and reconnect to resync the world.

Without more specifics, including your use case, I won't be considering either of these options.

**Comment by Rage-GitHub** [comment]
Uh, what? So you're not adding a feature for us to toggle so when a player does **/is delete** to not teleport them somewhere like spawn but instead let them fall to their death?

**Comment by Mohron** [comment]
I'd like you to find a player who would think being dropped into the void by a command was a feature and not a bug.  If you can't explain your use case and why this makes sense to offer, I won't be spending time on a "feature" that's going to ultimately be reported as a bug.

**Comment by Rage-GitHub** [comment]
I never said this was a bug, apparently you are the one having difficulty understanding this as I said specifically, 

> "It would be nice if you can toggle an option to either teleport players back to spawn after deleting it"

I don't know where you're getting the idea of this being a **bug** as I never even mentioned this being a bug. You're over complicating things lol.

**Comment by Mohron** [comment]
I know you're not reporting a bug. I'm saying what you're asking for is going to be considered as a bug by most players. You've still not done as I've asked and told me your use case so I can understand what you need better so we can ultimately find a middle ground.

At this point, I would probably just add a SkyClaims spawn point that you could configure separately of the world spawn to use for any action that relocates a player. If you choose to put this above the void, so be it.

Either way the better I understand your needs, the better I can design a solution that will provide value  to the most servers. At no point will I allow the plugin to leave the player in the region being regenerated due to the desync issues I already explained.
