### ISSUE TITLE
issues change the world that claims are generated in and config file resetting to default.

### ISSUE THREAD

**Issue by Nbgreen** [DevOnTheRocks/SkyClaims#138]
there was an issue similar, but it was 3 years old and was said to be fixed

### Version:
- **Sponge:** Sponge Forge 1.12.2-2838-7.4.7
- **SkyClaims:** SkyClaims-0.32.1-S7.13
- **GriefPrevention:** griefdefender-sponge-1.12.2-2.2.5
- **Permissions:** LuckPerms-Sponge-5.3.98

### Expected Behavior:

I set the world for the claims to generate in a world called skyclaims I expected it to generate there

### Actual Behavior:

it tried to gen the claims in the overworld
and resets the config back to default

### Steps To Reproduce:

change world in world setting 
start server

**Comment by Mohron** [comment]
If your configuration file is resetting, that generally means there was a parsing error due to the contents not matching the expected format. Please include your logs and config file.

**Comment by Nbgreen** [comment]
https://downloads.thebobsgamingnetwork.net/skyclaims.conf

https://downloads.thebobsgamingnetwork.net/latest.log

**Comment by Mohron** [comment]
The log file provided doesn't have any of SkyClaims' log messages. It does however show there is an issue between SkyClaims and Nucleus. Nucleus 2.X is expected if installed so that could be a problem but I can't say for sure without the relevant logs. You should see something like `SkyClaims 0.32.1-S7.13-GRIEF-DEFENDER-2 is initializing...` in your logs as it is logged before the nucleus integration code that left errors in your attached log file.

**Comment by Nbgreen** [comment]
updating nucleus fixed the issue
