### ISSUE TITLE
[Enhancement] Toggle PvP on Island

### ISSUE THREAD

**Issue by kaal-1** [DevOnTheRocks/SkyClaims#46]
Is there a way to add a command so that the owner of the island can toggle PvP on and off?

**Comment by Mohron** [comment]
This can be done using GP's PvP toggle in admin claim settings but that's not accessible to normal players. A setting like that is not usually one you let players control since it could be easily abused... A player could turn it on after another player comes onto their island in order to steal their stuff or could shut PvP off to avoid death on their own island. Either possibility likely contributed to GP's feature being made admin only and I'm not sure it would be a good move on my part to bypass that.

I'm going to need more specifics on your intentions if you want me to reconsider this request. As it stands now, I do not believe this would be a safe feature to add.

**Comment by kaal-1** [comment]
Ok, I understand your point. The intention was simply to allow more control on the islands, since the PvP on the server is turned on by default. Some players that do not like PVP asked if there was a way to disable it on their islands. I looked on both skyclaims and griefprevention wiki and couldn't find it.
I guess my best bet would be some plugin that toggles pvp for players specifically then.

**Comment by Mohron** [comment]
That would be my recommendation so one player can't control the pvp eligibility of another player
